#!/usr/bin/env python3
"""
Main translation script for the AIT Bible project.

Translates Greek biblical texts to English using Claude AI.
"""

import os
import sys
import time
import argparse
from pathlib import Path
from typing import Optional, Tuple

import anthropic

from greek_parser import GreekTextParser
from prompt_template import build_prompt


# Configuration
DEFAULT_MODEL = "claude-sonnet-4-5"  # Latest Sonnet model
MAX_TOKENS = 16000  # Must be > THINKING_BUDGET when thinking is enabled
THINKING_BUDGET = 10000  # Token budget for extended thinking
RATE_LIMIT_DELAY = 1.0  # Seconds between API calls to avoid rate limits


def get_client() -> anthropic.Anthropic:
    """Initialize the Anthropic client."""
    api_key = os.environ.get("ANTHROPIC_API_KEY")
    if not api_key:
        print("Error: ANTHROPIC_API_KEY environment variable not set.")
        print("Set it with: export ANTHROPIC_API_KEY='your-key-here'")
        sys.exit(1)
    
    return anthropic.Anthropic(api_key=api_key)


def translate_text(
    client: anthropic.Anthropic,
    greek_text: str,
    book_name: str,
    chapter_num: int,
    start_verse: Optional[int] = None,
    end_verse: Optional[int] = None,
    model: str = DEFAULT_MODEL,
    use_thinking: bool = False,
) -> str:
    """
    Translate Greek text to English using Claude.
    
    Args:
        client: Anthropic client
        greek_text: The Greek source text
        book_name: Name of the biblical book
        chapter_num: Chapter number
        start_verse: Starting verse (optional)
        end_verse: Ending verse (optional)
        model: Model to use for translation
        use_thinking: Whether to use extended thinking
    
    Returns:
        The translated English text with notes
    """
    prompt = build_prompt(
        source_text=greek_text,
        book_name=book_name,
        chapter_num=chapter_num,
        start_verse=start_verse,
        end_verse=end_verse,
    )
    
    # Build API call parameters
    api_params = {
        "model": model,
        "max_tokens": MAX_TOKENS,
        "messages": [
            {"role": "user", "content": prompt}
        ],
    }
    
    # Add extended thinking if requested
    if use_thinking:
        api_params["thinking"] = {
            "type": "enabled",
            "budget_tokens": THINKING_BUDGET,
        }
    
    message = client.messages.create(**api_params)
    
    # Extract text from response (skip thinking blocks)
    response_text = ""
    for block in message.content:
        if hasattr(block, "text") and block.type == "text":
            response_text += block.text
    
    return response_text


def save_translation(
    translation: str,
    book_name: str,
    chapter_num: int,
    output_dir: Path,
    start_verse: Optional[int] = None,
    end_verse: Optional[int] = None,
) -> Path:
    """
    Save a translation to a text file.
    
    Returns the path to the saved file.
    """
    # Create book directory
    book_dir = output_dir / book_name.lower()
    book_dir.mkdir(parents=True, exist_ok=True)
    
    # Determine filename
    if start_verse is not None and end_verse is not None:
        filename = f"chapter_{chapter_num:02d}_verses_{start_verse}-{end_verse}.txt"
    else:
        filename = f"chapter_{chapter_num:02d}.txt"
    
    filepath = book_dir / filename
    
    # Build file header
    header_lines = [
        f"# {book_name.title()} Chapter {chapter_num}",
    ]
    if start_verse is not None:
        header_lines.append(f"# Verses {start_verse}-{end_verse}")
    header_lines.extend([
        f"# AIT Bible Translation",
        f"# Generated by aitbible.org",
        "",
        "",
    ])
    header = "\n".join(header_lines)
    
    # Write file
    filepath.write_text(header + translation, encoding="utf-8")
    
    return filepath


def translate_chapter(
    client: anthropic.Anthropic,
    parser: GreekTextParser,
    book_name: str,
    chapter_num: int,
    output_dir: Path,
    model: str = DEFAULT_MODEL,
    start_verse: Optional[int] = None,
    end_verse: Optional[int] = None,
    use_thinking: bool = False,
) -> Path:
    """
    Translate a single chapter (or verse range) and save it.
    
    Returns the path to the saved file.
    """
    print(f"Translating {book_name.title()} {chapter_num}", end="")
    if start_verse is not None:
        print(f":{start_verse}-{end_verse}", end="")
    if use_thinking:
        print(" (with extended thinking)", end="")
    print("...")
    
    # Get Greek text
    if start_verse is not None and end_verse is not None:
        greek_text = parser.get_verse_range_text(
            book_name, chapter_num, start_verse, end_verse
        )
    else:
        greek_text = parser.get_chapter_text(book_name, chapter_num)
    
    # Translate
    translation = translate_text(
        client=client,
        greek_text=greek_text,
        book_name=book_name,
        chapter_num=chapter_num,
        start_verse=start_verse,
        end_verse=end_verse,
        model=model,
        use_thinking=use_thinking,
    )
    
    # Save
    filepath = save_translation(
        translation=translation,
        book_name=book_name,
        chapter_num=chapter_num,
        output_dir=output_dir,
        start_verse=start_verse,
        end_verse=end_verse,
    )
    
    print(f"  Saved to {filepath}")
    return filepath


def translate_book(
    client: anthropic.Anthropic,
    parser: GreekTextParser,
    book_name: str,
    output_dir: Path,
    model: str = DEFAULT_MODEL,
    use_thinking: bool = False,
) -> list[Path]:
    """
    Translate an entire book, chapter by chapter.
    
    Returns list of paths to saved files.
    """
    chapter_count = parser.get_chapter_count(book_name)
    print(f"Translating {book_name.title()} ({chapter_count} chapters)")
    if use_thinking:
        print("Extended thinking enabled")
    print()
    
    saved_files = []
    for chapter_num in range(1, chapter_count + 1):
        filepath = translate_chapter(
            client=client,
            parser=parser,
            book_name=book_name,
            chapter_num=chapter_num,
            output_dir=output_dir,
            model=model,
            use_thinking=use_thinking,
        )
        saved_files.append(filepath)
        
        # Rate limiting
        if chapter_num < chapter_count:
            time.sleep(RATE_LIMIT_DELAY)
    
    print(f"\nCompleted {book_name.title()}: {len(saved_files)} chapters translated.")
    return saved_files


def parse_verse_range(verse_str: str) -> Tuple[int, int]:
    """Parse a verse range string like '1-18' into (start, end)."""
    if "-" in verse_str:
        parts = verse_str.split("-")
        return int(parts[0]), int(parts[1])
    else:
        v = int(verse_str)
        return v, v


def main():
    arg_parser = argparse.ArgumentParser(
        description="Translate biblical Greek texts to English using Claude AI",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  %(prog)s --book matthew --chapter 6
  %(prog)s --book matthew --chapter 6 --verses 1-18
  %(prog)s --book matthew --all
  %(prog)s --book matthew --all --model claude-opus-4-5 --thinking
  %(prog)s --list-books
        """,
    )
    
    arg_parser.add_argument(
        "--book", "-b",
        help="Book name (e.g., 'matthew', 'john', '1corinthians')",
    )
    arg_parser.add_argument(
        "--chapter", "-c",
        type=int,
        help="Chapter number to translate",
    )
    arg_parser.add_argument(
        "--verses", "-v",
        help="Verse range (e.g., '1-18')",
    )
    arg_parser.add_argument(
        "--all", "-a",
        action="store_true",
        help="Translate all chapters in the book",
    )
    arg_parser.add_argument(
        "--output", "-o",
        default="output",
        help="Output directory (default: 'output')",
    )
    arg_parser.add_argument(
        "--greek-texts", "-g",
        default="greek_texts",
        help="Greek texts directory (default: 'greek_texts')",
    )
    arg_parser.add_argument(
        "--model", "-m",
        default=DEFAULT_MODEL,
        help=f"Claude model to use (default: {DEFAULT_MODEL})",
    )
    arg_parser.add_argument(
        "--thinking", "-t",
        action="store_true",
        help="Enable extended thinking for more deliberate translations",
    )
    arg_parser.add_argument(
        "--list-books",
        action="store_true",
        help="List available books and exit",
    )
    
    args = arg_parser.parse_args()
    
    # Initialize parser
    parser = GreekTextParser(args.greek_texts)
    
    # List books mode
    if args.list_books:
        print("Available books:")
        for book in parser.list_books():
            chapters = parser.get_chapter_count(book)
            print(f"  {book}: {chapters} chapters")
        return
    
    # Validate arguments
    if not args.book:
        arg_parser.error("--book is required (or use --list-books)")
    
    if not args.all and not args.chapter:
        arg_parser.error("Either --chapter or --all is required")
    
    # Initialize client
    client = get_client()
    output_dir = Path(args.output)
    
    # Translate
    if args.all:
        translate_book(
            client=client,
            parser=parser,
            book_name=args.book,
            output_dir=output_dir,
            model=args.model,
            use_thinking=args.thinking,
        )
    else:
        start_verse = None
        end_verse = None
        
        if args.verses:
            start_verse, end_verse = parse_verse_range(args.verses)
        
        translate_chapter(
            client=client,
            parser=parser,
            book_name=args.book,
            chapter_num=args.chapter,
            output_dir=output_dir,
            model=args.model,
            start_verse=start_verse,
            end_verse=end_verse,
            use_thinking=args.thinking,
        )


if __name__ == "__main__":
    main()